-- Dibuat otomatis dari skema akhir Postgres (supabase/migrations) untuk ADR-085. Jangan disunting; perubahan
-- skema berikutnya ditulis sebagai migrasi D1 baru (0003_..., dst.) dan lib/db/d1/skema.ts ikut diperbarui.

-- Jejak perubahan (ADR-084): isi lama setiap baris yang diubah atau dihapus disalin ke jejak_data oleh trigger,
-- dalam transaksi yang sama. Perubahan yang isinya sama tidak dicatat. Cron cadangan membuang jejak > 90 hari.
-- Catatan: json_patch membuang kunci bernilai null dari bagian kedua dan seterusnya; saat dipulihkan, kunci yang tidak
-- ada terbaca NULL, jadi hasilnya sama.

CREATE TRIGGER jejak_data_ubah_pegawai AFTER UPDATE ON pegawai FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.nip IS NOT NEW.nip OR OLD.nama IS NOT NEW.nama OR OLD.tempat_lahir IS NOT NEW.tempat_lahir OR OLD.tanggal_lahir IS NOT NEW.tanggal_lahir OR OLD.jenis_kelamin IS NOT NEW.jenis_kelamin OR OLD.pendidikan_terakhir IS NOT NEW.pendidikan_terakhir OR OLD.jabatan IS NOT NEW.jabatan OR OLD.pangkat IS NOT NEW.pangkat OR OLD.golongan_ruang IS NOT NEW.golongan_ruang OR OLD.unit_kerja IS NOT NEW.unit_kerja OR OLD.eselon IS NOT NEW.eselon OR OLD.jenis_jabatan IS NOT NEW.jenis_jabatan OR OLD.tmt_golongan IS NOT NEW.tmt_golongan OR OLD.mkg_tahun IS NOT NEW.mkg_tahun OR OLD.mkg_bulan IS NOT NEW.mkg_bulan OR OLD.gaji_pokok IS NOT NEW.gaji_pokok OR OLD.tmt_kgb_terakhir IS NOT NEW.tmt_kgb_terakhir OR OLD.tmt_kgb_berikutnya IS NOT NEW.tmt_kgb_berikutnya OR OLD.status_hukdis IS NOT NEW.status_hukdis OR OLD.tanggal_hukdis_berakhir IS NOT NEW.tanggal_hukdis_berakhir OR OLD.jenis_hukdis IS NOT NEW.jenis_hukdis OR OLD.keterangan_hukdis IS NOT NEW.keterangan_hukdis OR OLD.aktif IS NOT NEW.aktif OR OLD.created_at IS NOT NEW.created_at OR OLD.updated_at IS NOT NEW.updated_at OR OLD.urutan_sisip IS NOT NEW.urutan_sisip OR OLD.konfirmasi_upt_tmt IS NOT NEW.konfirmasi_upt_tmt OR OLD.konfirmasi_upt_at IS NOT NEW.konfirmasi_upt_at OR OLD.konfirmasi_upt_oleh IS NOT NEW.konfirmasi_upt_oleh OR OLD.satker_tugas IS NOT NEW.satker_tugas OR OLD.berhenti_tmt IS NOT NEW.berhenti_tmt OR OLD.berhenti_alasan IS NOT NEW.berhenti_alasan OR OLD.nomor_sk_dasar IS NOT NEW.nomor_sk_dasar OR OLD.tanggal_sk_dasar IS NOT NEW.tanggal_sk_dasar OR OLD.penetap_sk_dasar IS NOT NEW.penetap_sk_dasar
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('pegawai', 'ubah', OLD.id, json_patch(json_patch(json_object('id', OLD.id, 'nip', OLD.nip, 'nama', OLD.nama, 'tempat_lahir', OLD.tempat_lahir, 'tanggal_lahir', OLD.tanggal_lahir, 'jenis_kelamin', OLD.jenis_kelamin, 'pendidikan_terakhir', OLD.pendidikan_terakhir, 'jabatan', OLD.jabatan, 'pangkat', OLD.pangkat, 'golongan_ruang', OLD.golongan_ruang, 'unit_kerja', OLD.unit_kerja, 'eselon', OLD.eselon, 'jenis_jabatan', OLD.jenis_jabatan, 'tmt_golongan', OLD.tmt_golongan, 'mkg_tahun', OLD.mkg_tahun), json_object('mkg_bulan', OLD.mkg_bulan, 'gaji_pokok', OLD.gaji_pokok, 'tmt_kgb_terakhir', OLD.tmt_kgb_terakhir, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya, 'status_hukdis', OLD.status_hukdis, 'tanggal_hukdis_berakhir', OLD.tanggal_hukdis_berakhir, 'jenis_hukdis', OLD.jenis_hukdis, 'keterangan_hukdis', OLD.keterangan_hukdis, 'aktif', OLD.aktif, 'created_at', OLD.created_at, 'updated_at', OLD.updated_at, 'urutan_sisip', OLD.urutan_sisip, 'konfirmasi_upt_tmt', OLD.konfirmasi_upt_tmt, 'konfirmasi_upt_at', OLD.konfirmasi_upt_at, 'konfirmasi_upt_oleh', OLD.konfirmasi_upt_oleh)), json_object('satker_tugas', OLD.satker_tugas, 'berhenti_tmt', OLD.berhenti_tmt, 'berhenti_alasan', OLD.berhenti_alasan, 'nomor_sk_dasar', OLD.nomor_sk_dasar, 'tanggal_sk_dasar', OLD.tanggal_sk_dasar, 'penetap_sk_dasar', OLD.penetap_sk_dasar)));
END;

CREATE TRIGGER jejak_data_hapus_pegawai AFTER DELETE ON pegawai FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('pegawai', 'hapus', OLD.id, json_patch(json_patch(json_object('id', OLD.id, 'nip', OLD.nip, 'nama', OLD.nama, 'tempat_lahir', OLD.tempat_lahir, 'tanggal_lahir', OLD.tanggal_lahir, 'jenis_kelamin', OLD.jenis_kelamin, 'pendidikan_terakhir', OLD.pendidikan_terakhir, 'jabatan', OLD.jabatan, 'pangkat', OLD.pangkat, 'golongan_ruang', OLD.golongan_ruang, 'unit_kerja', OLD.unit_kerja, 'eselon', OLD.eselon, 'jenis_jabatan', OLD.jenis_jabatan, 'tmt_golongan', OLD.tmt_golongan, 'mkg_tahun', OLD.mkg_tahun), json_object('mkg_bulan', OLD.mkg_bulan, 'gaji_pokok', OLD.gaji_pokok, 'tmt_kgb_terakhir', OLD.tmt_kgb_terakhir, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya, 'status_hukdis', OLD.status_hukdis, 'tanggal_hukdis_berakhir', OLD.tanggal_hukdis_berakhir, 'jenis_hukdis', OLD.jenis_hukdis, 'keterangan_hukdis', OLD.keterangan_hukdis, 'aktif', OLD.aktif, 'created_at', OLD.created_at, 'updated_at', OLD.updated_at, 'urutan_sisip', OLD.urutan_sisip, 'konfirmasi_upt_tmt', OLD.konfirmasi_upt_tmt, 'konfirmasi_upt_at', OLD.konfirmasi_upt_at, 'konfirmasi_upt_oleh', OLD.konfirmasi_upt_oleh)), json_object('satker_tugas', OLD.satker_tugas, 'berhenti_tmt', OLD.berhenti_tmt, 'berhenti_alasan', OLD.berhenti_alasan, 'nomor_sk_dasar', OLD.nomor_sk_dasar, 'tanggal_sk_dasar', OLD.tanggal_sk_dasar, 'penetap_sk_dasar', OLD.penetap_sk_dasar)));
END;

CREATE TRIGGER jejak_data_ubah_riwayat_kgb AFTER UPDATE ON riwayat_kgb FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.nomor_sk IS NOT NEW.nomor_sk OR OLD.tanggal_sk IS NOT NEW.tanggal_sk OR OLD.tmt_sk IS NOT NEW.tmt_sk OR OLD.golongan_lama IS NOT NEW.golongan_lama OR OLD.gaji_pokok_lama IS NOT NEW.gaji_pokok_lama OR OLD.mkg_tahun_lama IS NOT NEW.mkg_tahun_lama OR OLD.mkg_bulan_lama IS NOT NEW.mkg_bulan_lama OR OLD.golongan_baru IS NOT NEW.golongan_baru OR OLD.gaji_pokok_baru IS NOT NEW.gaji_pokok_baru OR OLD.mkg_tahun_baru IS NOT NEW.mkg_tahun_baru OR OLD.mkg_bulan_baru IS NOT NEW.mkg_bulan_baru OR OLD.tmt_kgb_baru IS NOT NEW.tmt_kgb_baru OR OLD.tmt_kgb_berikutnya IS NOT NEW.tmt_kgb_berikutnya OR OLD.status IS NOT NEW.status OR OLD.flag_rapelan IS NOT NEW.flag_rapelan OR OLD.is_arsip IS NOT NEW.is_arsip OR OLD.konfirmasi_keuangan_at IS NOT NEW.konfirmasi_keuangan_at OR OLD.konfirmasi_keuangan_by IS NOT NEW.konfirmasi_keuangan_by OR OLD.rapelan_ditetapkan IS NOT NEW.rapelan_ditetapkan OR OLD.input_gaji_web_at IS NOT NEW.input_gaji_web_at OR OLD.input_gaji_web_by IS NOT NEW.input_gaji_web_by OR OLD.created_by IS NOT NEW.created_by OR OLD.created_at IS NOT NEW.created_at OR OLD.penetap_sk_dasar IS NOT NEW.penetap_sk_dasar OR OLD.urutan_sisip IS NOT NEW.urutan_sisip OR OLD.draf_nomor_surat IS NOT NEW.draf_nomor_surat OR OLD.draf_tanggal_surat IS NOT NEW.draf_tanggal_surat
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_kgb', 'ubah', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_sk', OLD.tmt_sk, 'golongan_lama', OLD.golongan_lama, 'gaji_pokok_lama', OLD.gaji_pokok_lama, 'mkg_tahun_lama', OLD.mkg_tahun_lama, 'mkg_bulan_lama', OLD.mkg_bulan_lama, 'golongan_baru', OLD.golongan_baru, 'gaji_pokok_baru', OLD.gaji_pokok_baru, 'mkg_tahun_baru', OLD.mkg_tahun_baru, 'mkg_bulan_baru', OLD.mkg_bulan_baru, 'tmt_kgb_baru', OLD.tmt_kgb_baru, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya), json_object('status', OLD.status, 'flag_rapelan', OLD.flag_rapelan, 'is_arsip', OLD.is_arsip, 'konfirmasi_keuangan_at', OLD.konfirmasi_keuangan_at, 'konfirmasi_keuangan_by', OLD.konfirmasi_keuangan_by, 'rapelan_ditetapkan', OLD.rapelan_ditetapkan, 'input_gaji_web_at', OLD.input_gaji_web_at, 'input_gaji_web_by', OLD.input_gaji_web_by, 'created_by', OLD.created_by, 'created_at', OLD.created_at, 'penetap_sk_dasar', OLD.penetap_sk_dasar, 'urutan_sisip', OLD.urutan_sisip, 'draf_nomor_surat', OLD.draf_nomor_surat, 'draf_tanggal_surat', OLD.draf_tanggal_surat)));
END;

CREATE TRIGGER jejak_data_hapus_riwayat_kgb AFTER DELETE ON riwayat_kgb FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_kgb', 'hapus', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_sk', OLD.tmt_sk, 'golongan_lama', OLD.golongan_lama, 'gaji_pokok_lama', OLD.gaji_pokok_lama, 'mkg_tahun_lama', OLD.mkg_tahun_lama, 'mkg_bulan_lama', OLD.mkg_bulan_lama, 'golongan_baru', OLD.golongan_baru, 'gaji_pokok_baru', OLD.gaji_pokok_baru, 'mkg_tahun_baru', OLD.mkg_tahun_baru, 'mkg_bulan_baru', OLD.mkg_bulan_baru, 'tmt_kgb_baru', OLD.tmt_kgb_baru, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya), json_object('status', OLD.status, 'flag_rapelan', OLD.flag_rapelan, 'is_arsip', OLD.is_arsip, 'konfirmasi_keuangan_at', OLD.konfirmasi_keuangan_at, 'konfirmasi_keuangan_by', OLD.konfirmasi_keuangan_by, 'rapelan_ditetapkan', OLD.rapelan_ditetapkan, 'input_gaji_web_at', OLD.input_gaji_web_at, 'input_gaji_web_by', OLD.input_gaji_web_by, 'created_by', OLD.created_by, 'created_at', OLD.created_at, 'penetap_sk_dasar', OLD.penetap_sk_dasar, 'urutan_sisip', OLD.urutan_sisip, 'draf_nomor_surat', OLD.draf_nomor_surat, 'draf_tanggal_surat', OLD.draf_tanggal_surat)));
END;

CREATE TRIGGER jejak_data_ubah_surat_kgb AFTER UPDATE ON surat_kgb FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.kgb_id IS NOT NEW.kgb_id OR OLD.nomor_surat IS NOT NEW.nomor_surat OR OLD.tanggal_surat IS NOT NEW.tanggal_surat OR OLD.nama_kepala_kanwil IS NOT NEW.nama_kepala_kanwil OR OLD.nip_kepala_kanwil IS NOT NEW.nip_kepala_kanwil OR OLD.path_file IS NOT NEW.path_file OR OLD.generated_at IS NOT NEW.generated_at OR OLD.generated_by IS NOT NEW.generated_by OR OLD.penandatangan_id IS NOT NEW.penandatangan_id OR OLD.jenis_penandatangan IS NOT NEW.jenis_penandatangan OR OLD.jabatan_penandatangan IS NOT NEW.jabatan_penandatangan OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('surat_kgb', 'ubah', OLD.id, json_object('id', OLD.id, 'kgb_id', OLD.kgb_id, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'nama_kepala_kanwil', OLD.nama_kepala_kanwil, 'nip_kepala_kanwil', OLD.nip_kepala_kanwil, 'path_file', OLD.path_file, 'generated_at', OLD.generated_at, 'generated_by', OLD.generated_by, 'penandatangan_id', OLD.penandatangan_id, 'jenis_penandatangan', OLD.jenis_penandatangan, 'jabatan_penandatangan', OLD.jabatan_penandatangan, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_surat_kgb AFTER DELETE ON surat_kgb FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('surat_kgb', 'hapus', OLD.id, json_object('id', OLD.id, 'kgb_id', OLD.kgb_id, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'nama_kepala_kanwil', OLD.nama_kepala_kanwil, 'nip_kepala_kanwil', OLD.nip_kepala_kanwil, 'path_file', OLD.path_file, 'generated_at', OLD.generated_at, 'generated_by', OLD.generated_by, 'penandatangan_id', OLD.penandatangan_id, 'jenis_penandatangan', OLD.jenis_penandatangan, 'jabatan_penandatangan', OLD.jabatan_penandatangan, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_serah_terima AFTER UPDATE ON serah_terima FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.kgb_id IS NOT NEW.kgb_id OR OLD.nama_admin IS NOT NEW.nama_admin OR OLD.keterangan IS NOT NEW.keterangan OR OLD.tanggal_serah_terima IS NOT NEW.tanggal_serah_terima OR OLD.created_by IS NOT NEW.created_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('serah_terima', 'ubah', OLD.id, json_object('id', OLD.id, 'kgb_id', OLD.kgb_id, 'nama_admin', OLD.nama_admin, 'keterangan', OLD.keterangan, 'tanggal_serah_terima', OLD.tanggal_serah_terima, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_serah_terima AFTER DELETE ON serah_terima FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('serah_terima', 'hapus', OLD.id, json_object('id', OLD.id, 'kgb_id', OLD.kgb_id, 'nama_admin', OLD.nama_admin, 'keterangan', OLD.keterangan, 'tanggal_serah_terima', OLD.tanggal_serah_terima, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_riwayat_pangkat AFTER UPDATE ON riwayat_pangkat FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.jenis_kp IS NOT NEW.jenis_kp OR OLD.nomor_sk IS NOT NEW.nomor_sk OR OLD.tanggal_sk IS NOT NEW.tanggal_sk OR OLD.tmt_pangkat IS NOT NEW.tmt_pangkat OR OLD.golongan_lama IS NOT NEW.golongan_lama OR OLD.golongan_baru IS NOT NEW.golongan_baru OR OLD.mkg_tahun_lama IS NOT NEW.mkg_tahun_lama OR OLD.mkg_bulan_lama IS NOT NEW.mkg_bulan_lama OR OLD.mkg_tahun_baru IS NOT NEW.mkg_tahun_baru OR OLD.mkg_bulan_baru IS NOT NEW.mkg_bulan_baru OR OLD.gaji_pokok_lama IS NOT NEW.gaji_pokok_lama OR OLD.gaji_pokok_baru IS NOT NEW.gaji_pokok_baru OR OLD.keterangan IS NOT NEW.keterangan OR OLD.created_at IS NOT NEW.created_at OR OLD.created_by IS NOT NEW.created_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip OR OLD.penetap_sk IS NOT NEW.penetap_sk
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_pangkat', 'ubah', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'jenis_kp', OLD.jenis_kp, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_pangkat', OLD.tmt_pangkat, 'golongan_lama', OLD.golongan_lama, 'golongan_baru', OLD.golongan_baru, 'mkg_tahun_lama', OLD.mkg_tahun_lama, 'mkg_bulan_lama', OLD.mkg_bulan_lama, 'mkg_tahun_baru', OLD.mkg_tahun_baru, 'mkg_bulan_baru', OLD.mkg_bulan_baru, 'gaji_pokok_lama', OLD.gaji_pokok_lama, 'gaji_pokok_baru', OLD.gaji_pokok_baru, 'keterangan', OLD.keterangan), json_object('created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip, 'penetap_sk', OLD.penetap_sk)));
END;

CREATE TRIGGER jejak_data_hapus_riwayat_pangkat AFTER DELETE ON riwayat_pangkat FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_pangkat', 'hapus', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'jenis_kp', OLD.jenis_kp, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_pangkat', OLD.tmt_pangkat, 'golongan_lama', OLD.golongan_lama, 'golongan_baru', OLD.golongan_baru, 'mkg_tahun_lama', OLD.mkg_tahun_lama, 'mkg_bulan_lama', OLD.mkg_bulan_lama, 'mkg_tahun_baru', OLD.mkg_tahun_baru, 'mkg_bulan_baru', OLD.mkg_bulan_baru, 'gaji_pokok_lama', OLD.gaji_pokok_lama, 'gaji_pokok_baru', OLD.gaji_pokok_baru, 'keterangan', OLD.keterangan), json_object('created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip, 'penetap_sk', OLD.penetap_sk)));
END;

CREATE TRIGGER jejak_data_ubah_riwayat_pmk AFTER UPDATE ON riwayat_pmk FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.nomor_sk IS NOT NEW.nomor_sk OR OLD.tanggal_sk IS NOT NEW.tanggal_sk OR OLD.tmt_pmk IS NOT NEW.tmt_pmk OR OLD.golongan_ruang IS NOT NEW.golongan_ruang OR OLD.tambah_bulan IS NOT NEW.tambah_bulan OR OLD.mkg_tahun_sebelum IS NOT NEW.mkg_tahun_sebelum OR OLD.mkg_bulan_sebelum IS NOT NEW.mkg_bulan_sebelum OR OLD.mkg_tahun_sesudah IS NOT NEW.mkg_tahun_sesudah OR OLD.mkg_bulan_sesudah IS NOT NEW.mkg_bulan_sesudah OR OLD.mkg_tahun_dasar_lama IS NOT NEW.mkg_tahun_dasar_lama OR OLD.mkg_bulan_dasar_lama IS NOT NEW.mkg_bulan_dasar_lama OR OLD.mkg_tahun_dasar_baru IS NOT NEW.mkg_tahun_dasar_baru OR OLD.mkg_bulan_dasar_baru IS NOT NEW.mkg_bulan_dasar_baru OR OLD.gaji_pokok_lama IS NOT NEW.gaji_pokok_lama OR OLD.gaji_pokok_baru IS NOT NEW.gaji_pokok_baru OR OLD.tmt_kgb_berikutnya_lama IS NOT NEW.tmt_kgb_berikutnya_lama OR OLD.tmt_kgb_berikutnya_baru IS NOT NEW.tmt_kgb_berikutnya_baru OR OLD.penetap_sk IS NOT NEW.penetap_sk OR OLD.keterangan IS NOT NEW.keterangan OR OLD.created_at IS NOT NEW.created_at OR OLD.created_by IS NOT NEW.created_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_pmk', 'ubah', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_pmk', OLD.tmt_pmk, 'golongan_ruang', OLD.golongan_ruang, 'tambah_bulan', OLD.tambah_bulan, 'mkg_tahun_sebelum', OLD.mkg_tahun_sebelum, 'mkg_bulan_sebelum', OLD.mkg_bulan_sebelum, 'mkg_tahun_sesudah', OLD.mkg_tahun_sesudah, 'mkg_bulan_sesudah', OLD.mkg_bulan_sesudah, 'mkg_tahun_dasar_lama', OLD.mkg_tahun_dasar_lama, 'mkg_bulan_dasar_lama', OLD.mkg_bulan_dasar_lama, 'mkg_tahun_dasar_baru', OLD.mkg_tahun_dasar_baru, 'mkg_bulan_dasar_baru', OLD.mkg_bulan_dasar_baru), json_object('gaji_pokok_lama', OLD.gaji_pokok_lama, 'gaji_pokok_baru', OLD.gaji_pokok_baru, 'tmt_kgb_berikutnya_lama', OLD.tmt_kgb_berikutnya_lama, 'tmt_kgb_berikutnya_baru', OLD.tmt_kgb_berikutnya_baru, 'penetap_sk', OLD.penetap_sk, 'keterangan', OLD.keterangan, 'created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip)));
END;

CREATE TRIGGER jejak_data_hapus_riwayat_pmk AFTER DELETE ON riwayat_pmk FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_pmk', 'hapus', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_pmk', OLD.tmt_pmk, 'golongan_ruang', OLD.golongan_ruang, 'tambah_bulan', OLD.tambah_bulan, 'mkg_tahun_sebelum', OLD.mkg_tahun_sebelum, 'mkg_bulan_sebelum', OLD.mkg_bulan_sebelum, 'mkg_tahun_sesudah', OLD.mkg_tahun_sesudah, 'mkg_bulan_sesudah', OLD.mkg_bulan_sesudah, 'mkg_tahun_dasar_lama', OLD.mkg_tahun_dasar_lama, 'mkg_bulan_dasar_lama', OLD.mkg_bulan_dasar_lama, 'mkg_tahun_dasar_baru', OLD.mkg_tahun_dasar_baru, 'mkg_bulan_dasar_baru', OLD.mkg_bulan_dasar_baru), json_object('gaji_pokok_lama', OLD.gaji_pokok_lama, 'gaji_pokok_baru', OLD.gaji_pokok_baru, 'tmt_kgb_berikutnya_lama', OLD.tmt_kgb_berikutnya_lama, 'tmt_kgb_berikutnya_baru', OLD.tmt_kgb_berikutnya_baru, 'penetap_sk', OLD.penetap_sk, 'keterangan', OLD.keterangan, 'created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip)));
END;

CREATE TRIGGER jejak_data_ubah_riwayat_hukdis AFTER UPDATE ON riwayat_hukdis FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.jenis_hukdis IS NOT NEW.jenis_hukdis OR OLD.nomor_sk IS NOT NEW.nomor_sk OR OLD.tanggal_sk IS NOT NEW.tanggal_sk OR OLD.tmt_mulai IS NOT NEW.tmt_mulai OR OLD.tmt_berakhir IS NOT NEW.tmt_berakhir OR OLD.berdampak_kgb IS NOT NEW.berdampak_kgb OR OLD.durasi_tunda IS NOT NEW.durasi_tunda OR OLD.dasar_hukum IS NOT NEW.dasar_hukum OR OLD.keterangan IS NOT NEW.keterangan OR OLD.created_at IS NOT NEW.created_at OR OLD.created_by IS NOT NEW.created_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_hukdis', 'ubah', OLD.id, json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'jenis_hukdis', OLD.jenis_hukdis, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_mulai', OLD.tmt_mulai, 'tmt_berakhir', OLD.tmt_berakhir, 'berdampak_kgb', OLD.berdampak_kgb, 'durasi_tunda', OLD.durasi_tunda, 'dasar_hukum', OLD.dasar_hukum, 'keterangan', OLD.keterangan, 'created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_riwayat_hukdis AFTER DELETE ON riwayat_hukdis FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_hukdis', 'hapus', OLD.id, json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'jenis_hukdis', OLD.jenis_hukdis, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_mulai', OLD.tmt_mulai, 'tmt_berakhir', OLD.tmt_berakhir, 'berdampak_kgb', OLD.berdampak_kgb, 'durasi_tunda', OLD.durasi_tunda, 'dasar_hukum', OLD.dasar_hukum, 'keterangan', OLD.keterangan, 'created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_riwayat_mutasi AFTER UPDATE ON riwayat_mutasi FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.jenis IS NOT NEW.jenis OR OLD.satker_asal IS NOT NEW.satker_asal OR OLD.satker_tujuan IS NOT NEW.satker_tujuan OR OLD.tmt IS NOT NEW.tmt OR OLD.nomor_sk IS NOT NEW.nomor_sk OR OLD.tanggal_sk IS NOT NEW.tanggal_sk OR OLD.alasan IS NOT NEW.alasan OR OLD.keterangan IS NOT NEW.keterangan OR OLD.created_at IS NOT NEW.created_at OR OLD.created_by IS NOT NEW.created_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_mutasi', 'ubah', OLD.id, json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'jenis', OLD.jenis, 'satker_asal', OLD.satker_asal, 'satker_tujuan', OLD.satker_tujuan, 'tmt', OLD.tmt, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'alasan', OLD.alasan, 'keterangan', OLD.keterangan, 'created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_riwayat_mutasi AFTER DELETE ON riwayat_mutasi FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('riwayat_mutasi', 'hapus', OLD.id, json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'jenis', OLD.jenis, 'satker_asal', OLD.satker_asal, 'satker_tujuan', OLD.satker_tujuan, 'tmt', OLD.tmt, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'alasan', OLD.alasan, 'keterangan', OLD.keterangan, 'created_at', OLD.created_at, 'created_by', OLD.created_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_usulan_pegawai AFTER UPDATE ON usulan_pegawai FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.satker IS NOT NEW.satker OR OLD.status IS NOT NEW.status OR OLD.nomor_surat IS NOT NEW.nomor_surat OR OLD.tanggal_surat IS NOT NEW.tanggal_surat OR OLD.path_berkas IS NOT NEW.path_berkas OR OLD.nama IS NOT NEW.nama OR OLD.tempat_lahir IS NOT NEW.tempat_lahir OR OLD.tanggal_lahir IS NOT NEW.tanggal_lahir OR OLD.jenis_kelamin IS NOT NEW.jenis_kelamin OR OLD.pendidikan_terakhir IS NOT NEW.pendidikan_terakhir OR OLD.jabatan IS NOT NEW.jabatan OR OLD.pangkat IS NOT NEW.pangkat OR OLD.golongan_ruang IS NOT NEW.golongan_ruang OR OLD.eselon IS NOT NEW.eselon OR OLD.jenis_jabatan IS NOT NEW.jenis_jabatan OR OLD.tmt_golongan IS NOT NEW.tmt_golongan OR OLD.mkg_tahun IS NOT NEW.mkg_tahun OR OLD.mkg_bulan IS NOT NEW.mkg_bulan OR OLD.gaji_pokok IS NOT NEW.gaji_pokok OR OLD.tmt_kgb_terakhir IS NOT NEW.tmt_kgb_terakhir OR OLD.tmt_kgb_berikutnya IS NOT NEW.tmt_kgb_berikutnya OR OLD.nomor_sk_terakhir IS NOT NEW.nomor_sk_terakhir OR OLD.tanggal_sk_terakhir IS NOT NEW.tanggal_sk_terakhir OR OLD.hukdis_ada IS NOT NEW.hukdis_ada OR OLD.hukdis_jenis IS NOT NEW.hukdis_jenis OR OLD.hukdis_nomor_sk IS NOT NEW.hukdis_nomor_sk OR OLD.hukdis_tmt_mulai IS NOT NEW.hukdis_tmt_mulai OR OLD.hukdis_tmt_berakhir IS NOT NEW.hukdis_tmt_berakhir OR OLD.hukdis_keterangan IS NOT NEW.hukdis_keterangan OR OLD.catatan_upt IS NOT NEW.catatan_upt OR OLD.diajukan_oleh IS NOT NEW.diajukan_oleh OR OLD.diajukan_at IS NOT NEW.diajukan_at OR OLD.ditinjau_oleh IS NOT NEW.ditinjau_oleh OR OLD.ditinjau_at IS NOT NEW.ditinjau_at OR OLD.alasan_tolak IS NOT NEW.alasan_tolak OR OLD.urutan_sisip IS NOT NEW.urutan_sisip OR OLD.jenis IS NOT NEW.jenis OR OLD.nip IS NOT NEW.nip OR OLD.unit_kerja IS NOT NEW.unit_kerja OR OLD.path_sk_terakhir IS NOT NEW.path_sk_terakhir OR OLD.path_syarat_cpns IS NOT NEW.path_syarat_cpns OR OLD.path_sk_pangkat IS NOT NEW.path_sk_pangkat OR OLD.path_sk_cpns IS NOT NEW.path_sk_cpns OR OLD.dasar_baru_jenis IS NOT NEW.dasar_baru_jenis OR OLD.dasar_baru_jenis_kp IS NOT NEW.dasar_baru_jenis_kp OR OLD.dasar_baru_nomor_sk IS NOT NEW.dasar_baru_nomor_sk OR OLD.dasar_baru_tanggal_sk IS NOT NEW.dasar_baru_tanggal_sk OR OLD.dasar_baru_tmt IS NOT NEW.dasar_baru_tmt OR OLD.dasar_baru_penetap IS NOT NEW.dasar_baru_penetap OR OLD.path_sk_pmk IS NOT NEW.path_sk_pmk OR OLD.golongan_acuan IS NOT NEW.golongan_acuan OR OLD.mkg_tahun_acuan IS NOT NEW.mkg_tahun_acuan OR OLD.mkg_bulan_acuan IS NOT NEW.mkg_bulan_acuan OR OLD.keadaan_kgb IS NOT NEW.keadaan_kgb
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('usulan_pegawai', 'ubah', OLD.id, json_patch(json_patch(json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'status', OLD.status, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'path_berkas', OLD.path_berkas, 'nama', OLD.nama, 'tempat_lahir', OLD.tempat_lahir, 'tanggal_lahir', OLD.tanggal_lahir, 'jenis_kelamin', OLD.jenis_kelamin, 'pendidikan_terakhir', OLD.pendidikan_terakhir, 'jabatan', OLD.jabatan, 'pangkat', OLD.pangkat, 'golongan_ruang', OLD.golongan_ruang), json_object('eselon', OLD.eselon, 'jenis_jabatan', OLD.jenis_jabatan, 'tmt_golongan', OLD.tmt_golongan, 'mkg_tahun', OLD.mkg_tahun, 'mkg_bulan', OLD.mkg_bulan, 'gaji_pokok', OLD.gaji_pokok, 'tmt_kgb_terakhir', OLD.tmt_kgb_terakhir, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya, 'nomor_sk_terakhir', OLD.nomor_sk_terakhir, 'tanggal_sk_terakhir', OLD.tanggal_sk_terakhir, 'hukdis_ada', OLD.hukdis_ada, 'hukdis_jenis', OLD.hukdis_jenis, 'hukdis_nomor_sk', OLD.hukdis_nomor_sk, 'hukdis_tmt_mulai', OLD.hukdis_tmt_mulai, 'hukdis_tmt_berakhir', OLD.hukdis_tmt_berakhir)), json_object('hukdis_keterangan', OLD.hukdis_keterangan, 'catatan_upt', OLD.catatan_upt, 'diajukan_oleh', OLD.diajukan_oleh, 'diajukan_at', OLD.diajukan_at, 'ditinjau_oleh', OLD.ditinjau_oleh, 'ditinjau_at', OLD.ditinjau_at, 'alasan_tolak', OLD.alasan_tolak, 'urutan_sisip', OLD.urutan_sisip, 'jenis', OLD.jenis, 'nip', OLD.nip, 'unit_kerja', OLD.unit_kerja, 'path_sk_terakhir', OLD.path_sk_terakhir, 'path_syarat_cpns', OLD.path_syarat_cpns, 'path_sk_pangkat', OLD.path_sk_pangkat, 'path_sk_cpns', OLD.path_sk_cpns)), json_object('dasar_baru_jenis', OLD.dasar_baru_jenis, 'dasar_baru_jenis_kp', OLD.dasar_baru_jenis_kp, 'dasar_baru_nomor_sk', OLD.dasar_baru_nomor_sk, 'dasar_baru_tanggal_sk', OLD.dasar_baru_tanggal_sk, 'dasar_baru_tmt', OLD.dasar_baru_tmt, 'dasar_baru_penetap', OLD.dasar_baru_penetap, 'path_sk_pmk', OLD.path_sk_pmk, 'golongan_acuan', OLD.golongan_acuan, 'mkg_tahun_acuan', OLD.mkg_tahun_acuan, 'mkg_bulan_acuan', OLD.mkg_bulan_acuan, 'keadaan_kgb', OLD.keadaan_kgb)));
END;

CREATE TRIGGER jejak_data_hapus_usulan_pegawai AFTER DELETE ON usulan_pegawai FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('usulan_pegawai', 'hapus', OLD.id, json_patch(json_patch(json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'status', OLD.status, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'path_berkas', OLD.path_berkas, 'nama', OLD.nama, 'tempat_lahir', OLD.tempat_lahir, 'tanggal_lahir', OLD.tanggal_lahir, 'jenis_kelamin', OLD.jenis_kelamin, 'pendidikan_terakhir', OLD.pendidikan_terakhir, 'jabatan', OLD.jabatan, 'pangkat', OLD.pangkat, 'golongan_ruang', OLD.golongan_ruang), json_object('eselon', OLD.eselon, 'jenis_jabatan', OLD.jenis_jabatan, 'tmt_golongan', OLD.tmt_golongan, 'mkg_tahun', OLD.mkg_tahun, 'mkg_bulan', OLD.mkg_bulan, 'gaji_pokok', OLD.gaji_pokok, 'tmt_kgb_terakhir', OLD.tmt_kgb_terakhir, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya, 'nomor_sk_terakhir', OLD.nomor_sk_terakhir, 'tanggal_sk_terakhir', OLD.tanggal_sk_terakhir, 'hukdis_ada', OLD.hukdis_ada, 'hukdis_jenis', OLD.hukdis_jenis, 'hukdis_nomor_sk', OLD.hukdis_nomor_sk, 'hukdis_tmt_mulai', OLD.hukdis_tmt_mulai, 'hukdis_tmt_berakhir', OLD.hukdis_tmt_berakhir)), json_object('hukdis_keterangan', OLD.hukdis_keterangan, 'catatan_upt', OLD.catatan_upt, 'diajukan_oleh', OLD.diajukan_oleh, 'diajukan_at', OLD.diajukan_at, 'ditinjau_oleh', OLD.ditinjau_oleh, 'ditinjau_at', OLD.ditinjau_at, 'alasan_tolak', OLD.alasan_tolak, 'urutan_sisip', OLD.urutan_sisip, 'jenis', OLD.jenis, 'nip', OLD.nip, 'unit_kerja', OLD.unit_kerja, 'path_sk_terakhir', OLD.path_sk_terakhir, 'path_syarat_cpns', OLD.path_syarat_cpns, 'path_sk_pangkat', OLD.path_sk_pangkat, 'path_sk_cpns', OLD.path_sk_cpns)), json_object('dasar_baru_jenis', OLD.dasar_baru_jenis, 'dasar_baru_jenis_kp', OLD.dasar_baru_jenis_kp, 'dasar_baru_nomor_sk', OLD.dasar_baru_nomor_sk, 'dasar_baru_tanggal_sk', OLD.dasar_baru_tanggal_sk, 'dasar_baru_tmt', OLD.dasar_baru_tmt, 'dasar_baru_penetap', OLD.dasar_baru_penetap, 'path_sk_pmk', OLD.path_sk_pmk, 'golongan_acuan', OLD.golongan_acuan, 'mkg_tahun_acuan', OLD.mkg_tahun_acuan, 'mkg_bulan_acuan', OLD.mkg_bulan_acuan, 'keadaan_kgb', OLD.keadaan_kgb)));
END;

CREATE TRIGGER jejak_data_ubah_laporan_mutasi AFTER UPDATE ON laporan_mutasi FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.satker IS NOT NEW.satker OR OLD.jenis IS NOT NEW.jenis OR OLD.satker_tujuan IS NOT NEW.satker_tujuan OR OLD.tmt IS NOT NEW.tmt OR OLD.nomor_sk IS NOT NEW.nomor_sk OR OLD.tanggal_sk IS NOT NEW.tanggal_sk OR OLD.alasan IS NOT NEW.alasan OR OLD.keterangan IS NOT NEW.keterangan OR OLD.status IS NOT NEW.status OR OLD.catatan_kanwil IS NOT NEW.catatan_kanwil OR OLD.dilaporkan_oleh IS NOT NEW.dilaporkan_oleh OR OLD.dilaporkan_at IS NOT NEW.dilaporkan_at OR OLD.ditinjau_oleh IS NOT NEW.ditinjau_oleh OR OLD.ditinjau_at IS NOT NEW.ditinjau_at OR OLD.riwayat_id IS NOT NEW.riwayat_id OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('laporan_mutasi', 'ubah', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'jenis', OLD.jenis, 'satker_tujuan', OLD.satker_tujuan, 'tmt', OLD.tmt, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'alasan', OLD.alasan, 'keterangan', OLD.keterangan, 'status', OLD.status, 'catatan_kanwil', OLD.catatan_kanwil, 'dilaporkan_oleh', OLD.dilaporkan_oleh, 'dilaporkan_at', OLD.dilaporkan_at, 'ditinjau_oleh', OLD.ditinjau_oleh), json_object('ditinjau_at', OLD.ditinjau_at, 'riwayat_id', OLD.riwayat_id, 'urutan_sisip', OLD.urutan_sisip)));
END;

CREATE TRIGGER jejak_data_hapus_laporan_mutasi AFTER DELETE ON laporan_mutasi FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('laporan_mutasi', 'hapus', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'jenis', OLD.jenis, 'satker_tujuan', OLD.satker_tujuan, 'tmt', OLD.tmt, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'alasan', OLD.alasan, 'keterangan', OLD.keterangan, 'status', OLD.status, 'catatan_kanwil', OLD.catatan_kanwil, 'dilaporkan_oleh', OLD.dilaporkan_oleh, 'dilaporkan_at', OLD.dilaporkan_at, 'ditinjau_oleh', OLD.ditinjau_oleh), json_object('ditinjau_at', OLD.ditinjau_at, 'riwayat_id', OLD.riwayat_id, 'urutan_sisip', OLD.urutan_sisip)));
END;

CREATE TRIGGER jejak_data_ubah_laporan_hukdis AFTER UPDATE ON laporan_hukdis FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.satker IS NOT NEW.satker OR OLD.jenis_hukdis IS NOT NEW.jenis_hukdis OR OLD.nomor_sk IS NOT NEW.nomor_sk OR OLD.tanggal_sk IS NOT NEW.tanggal_sk OR OLD.tmt_mulai IS NOT NEW.tmt_mulai OR OLD.tmt_berakhir IS NOT NEW.tmt_berakhir OR OLD.keterangan IS NOT NEW.keterangan OR OLD.path_berkas IS NOT NEW.path_berkas OR OLD.status IS NOT NEW.status OR OLD.catatan_kanwil IS NOT NEW.catatan_kanwil OR OLD.dilaporkan_oleh IS NOT NEW.dilaporkan_oleh OR OLD.dilaporkan_at IS NOT NEW.dilaporkan_at OR OLD.ditinjau_oleh IS NOT NEW.ditinjau_oleh OR OLD.ditinjau_at IS NOT NEW.ditinjau_at OR OLD.riwayat_id IS NOT NEW.riwayat_id OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('laporan_hukdis', 'ubah', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'jenis_hukdis', OLD.jenis_hukdis, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_mulai', OLD.tmt_mulai, 'tmt_berakhir', OLD.tmt_berakhir, 'keterangan', OLD.keterangan, 'path_berkas', OLD.path_berkas, 'status', OLD.status, 'catatan_kanwil', OLD.catatan_kanwil, 'dilaporkan_oleh', OLD.dilaporkan_oleh, 'dilaporkan_at', OLD.dilaporkan_at, 'ditinjau_oleh', OLD.ditinjau_oleh), json_object('ditinjau_at', OLD.ditinjau_at, 'riwayat_id', OLD.riwayat_id, 'urutan_sisip', OLD.urutan_sisip)));
END;

CREATE TRIGGER jejak_data_hapus_laporan_hukdis AFTER DELETE ON laporan_hukdis FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('laporan_hukdis', 'hapus', OLD.id, json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'jenis_hukdis', OLD.jenis_hukdis, 'nomor_sk', OLD.nomor_sk, 'tanggal_sk', OLD.tanggal_sk, 'tmt_mulai', OLD.tmt_mulai, 'tmt_berakhir', OLD.tmt_berakhir, 'keterangan', OLD.keterangan, 'path_berkas', OLD.path_berkas, 'status', OLD.status, 'catatan_kanwil', OLD.catatan_kanwil, 'dilaporkan_oleh', OLD.dilaporkan_oleh, 'dilaporkan_at', OLD.dilaporkan_at, 'ditinjau_oleh', OLD.ditinjau_oleh), json_object('ditinjau_at', OLD.ditinjau_at, 'riwayat_id', OLD.riwayat_id, 'urutan_sisip', OLD.urutan_sisip)));
END;

CREATE TRIGGER jejak_data_ubah_review_sk_upt AFTER UPDATE ON review_sk_upt FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.satker IS NOT NEW.satker OR OLD.status IS NOT NEW.status OR OLD.versi IS NOT NEW.versi OR OLD.nomor_surat IS NOT NEW.nomor_surat OR OLD.tanggal_surat IS NOT NEW.tanggal_surat OR OLD.diminta_at IS NOT NEW.diminta_at OR OLD.diminta_oleh IS NOT NEW.diminta_oleh OR OLD.ditanggapi_at IS NOT NEW.ditanggapi_at OR OLD.ditanggapi_oleh IS NOT NEW.ditanggapi_oleh OR OLD.catatan IS NOT NEW.catatan OR OLD.alasan_lewati IS NOT NEW.alasan_lewati OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('review_sk_upt', 'ubah', OLD.id, json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'status', OLD.status, 'versi', OLD.versi, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'diminta_at', OLD.diminta_at, 'diminta_oleh', OLD.diminta_oleh, 'ditanggapi_at', OLD.ditanggapi_at, 'ditanggapi_oleh', OLD.ditanggapi_oleh, 'catatan', OLD.catatan, 'alasan_lewati', OLD.alasan_lewati, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_review_sk_upt AFTER DELETE ON review_sk_upt FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('review_sk_upt', 'hapus', OLD.id, json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'status', OLD.status, 'versi', OLD.versi, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'diminta_at', OLD.diminta_at, 'diminta_oleh', OLD.diminta_oleh, 'ditanggapi_at', OLD.ditanggapi_at, 'ditanggapi_oleh', OLD.ditanggapi_oleh, 'catatan', OLD.catatan, 'alasan_lewati', OLD.alasan_lewati, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_penandatangan AFTER UPDATE ON penandatangan FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.jenis IS NOT NEW.jenis OR OLD.nama IS NOT NEW.nama OR OLD.nip IS NOT NEW.nip OR OLD.jabatan IS NOT NEW.jabatan OR OLD.dasar_penunjukan IS NOT NEW.dasar_penunjukan OR OLD.berlaku_mulai IS NOT NEW.berlaku_mulai OR OLD.berlaku_sampai IS NOT NEW.berlaku_sampai OR OLD.updated_at IS NOT NEW.updated_at OR OLD.updated_by IS NOT NEW.updated_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('penandatangan', 'ubah', OLD.id, json_object('id', OLD.id, 'jenis', OLD.jenis, 'nama', OLD.nama, 'nip', OLD.nip, 'jabatan', OLD.jabatan, 'dasar_penunjukan', OLD.dasar_penunjukan, 'berlaku_mulai', OLD.berlaku_mulai, 'berlaku_sampai', OLD.berlaku_sampai, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_penandatangan AFTER DELETE ON penandatangan FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('penandatangan', 'hapus', OLD.id, json_object('id', OLD.id, 'jenis', OLD.jenis, 'nama', OLD.nama, 'nip', OLD.nip, 'jabatan', OLD.jabatan, 'dasar_penunjukan', OLD.dasar_penunjukan, 'berlaku_mulai', OLD.berlaku_mulai, 'berlaku_sampai', OLD.berlaku_sampai, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_template_surat AFTER UPDATE ON template_surat FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.versi IS NOT NEW.versi OR OLD.berlaku_mulai IS NOT NEW.berlaku_mulai OR OLD.isi IS NOT NEW.isi OR OLD.catatan IS NOT NEW.catatan OR OLD.dibuat_oleh IS NOT NEW.dibuat_oleh OR OLD.dibuat_at IS NOT NEW.dibuat_at OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('template_surat', 'ubah', OLD.id, json_object('id', OLD.id, 'versi', OLD.versi, 'berlaku_mulai', OLD.berlaku_mulai, 'isi', OLD.isi, 'catatan', OLD.catatan, 'dibuat_oleh', OLD.dibuat_oleh, 'dibuat_at', OLD.dibuat_at, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_template_surat AFTER DELETE ON template_surat FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('template_surat', 'hapus', OLD.id, json_object('id', OLD.id, 'versi', OLD.versi, 'berlaku_mulai', OLD.berlaku_mulai, 'isi', OLD.isi, 'catatan', OLD.catatan, 'dibuat_oleh', OLD.dibuat_oleh, 'dibuat_at', OLD.dibuat_at, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_konfigurasi_kanwil AFTER UPDATE ON konfigurasi_kanwil FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.nama_kepala IS NOT NEW.nama_kepala OR OLD.nip_kepala IS NOT NEW.nip_kepala OR OLD.nomor_pp IS NOT NEW.nomor_pp OR OLD.tahun_pp IS NOT NEW.tahun_pp OR OLD.wa_admin IS NOT NEW.wa_admin OR OLD.notif_kgb_h1 IS NOT NEW.notif_kgb_h1 OR OLD.notif_kgb_h2 IS NOT NEW.notif_kgb_h2 OR OLD.sesi_timeout_menit IS NOT NEW.sesi_timeout_menit OR OLD.updated_at IS NOT NEW.updated_at OR OLD.updated_by IS NOT NEW.updated_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip OR OLD.batas_input_sdm IS NOT NEW.batas_input_sdm OR OLD.kppn_satker IS NOT NEW.kppn_satker
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('konfigurasi_kanwil', 'ubah', OLD.id, json_object('id', OLD.id, 'nama_kepala', OLD.nama_kepala, 'nip_kepala', OLD.nip_kepala, 'nomor_pp', OLD.nomor_pp, 'tahun_pp', OLD.tahun_pp, 'wa_admin', OLD.wa_admin, 'notif_kgb_h1', OLD.notif_kgb_h1, 'notif_kgb_h2', OLD.notif_kgb_h2, 'sesi_timeout_menit', OLD.sesi_timeout_menit, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip, 'batas_input_sdm', OLD.batas_input_sdm, 'kppn_satker', OLD.kppn_satker));
END;

CREATE TRIGGER jejak_data_hapus_konfigurasi_kanwil AFTER DELETE ON konfigurasi_kanwil FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('konfigurasi_kanwil', 'hapus', OLD.id, json_object('id', OLD.id, 'nama_kepala', OLD.nama_kepala, 'nip_kepala', OLD.nip_kepala, 'nomor_pp', OLD.nomor_pp, 'tahun_pp', OLD.tahun_pp, 'wa_admin', OLD.wa_admin, 'notif_kgb_h1', OLD.notif_kgb_h1, 'notif_kgb_h2', OLD.notif_kgb_h2, 'sesi_timeout_menit', OLD.sesi_timeout_menit, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip, 'batas_input_sdm', OLD.batas_input_sdm, 'kppn_satker', OLD.kppn_satker));
END;

CREATE TRIGGER jejak_data_ubah_hukdis_jenis AFTER UPDATE ON hukdis_jenis FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.kode IS NOT NEW.kode OR OLD.label IS NOT NEW.label OR OLD.kategori IS NOT NEW.kategori OR OLD.dasar_hukum IS NOT NEW.dasar_hukum OR OLD.regulasi_id IS NOT NEW.regulasi_id OR OLD.durasi_hukdis IS NOT NEW.durasi_hukdis OR OLD.berdampak_kgb IS NOT NEW.berdampak_kgb OR OLD.durasi_tunda IS NOT NEW.durasi_tunda OR OLD.aktif IS NOT NEW.aktif OR OLD.urutan IS NOT NEW.urutan OR OLD.updated_at IS NOT NEW.updated_at OR OLD.updated_by IS NOT NEW.updated_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('hukdis_jenis', 'ubah', OLD.id, json_object('id', OLD.id, 'kode', OLD.kode, 'label', OLD.label, 'kategori', OLD.kategori, 'dasar_hukum', OLD.dasar_hukum, 'regulasi_id', OLD.regulasi_id, 'durasi_hukdis', OLD.durasi_hukdis, 'berdampak_kgb', OLD.berdampak_kgb, 'durasi_tunda', OLD.durasi_tunda, 'aktif', OLD.aktif, 'urutan', OLD.urutan, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_hukdis_jenis AFTER DELETE ON hukdis_jenis FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('hukdis_jenis', 'hapus', OLD.id, json_object('id', OLD.id, 'kode', OLD.kode, 'label', OLD.label, 'kategori', OLD.kategori, 'dasar_hukum', OLD.dasar_hukum, 'regulasi_id', OLD.regulasi_id, 'durasi_hukdis', OLD.durasi_hukdis, 'berdampak_kgb', OLD.berdampak_kgb, 'durasi_tunda', OLD.durasi_tunda, 'aktif', OLD.aktif, 'urutan', OLD.urutan, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_hukdis_konfigurasi AFTER UPDATE ON hukdis_konfigurasi FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.notif_hari_h1 IS NOT NEW.notif_hari_h1 OR OLD.notif_hari_h2 IS NOT NEW.notif_hari_h2 OR OLD.updated_at IS NOT NEW.updated_at OR OLD.updated_by IS NOT NEW.updated_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('hukdis_konfigurasi', 'ubah', OLD.id, json_object('id', OLD.id, 'notif_hari_h1', OLD.notif_hari_h1, 'notif_hari_h2', OLD.notif_hari_h2, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_hukdis_konfigurasi AFTER DELETE ON hukdis_konfigurasi FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('hukdis_konfigurasi', 'hapus', OLD.id, json_object('id', OLD.id, 'notif_hari_h1', OLD.notif_hari_h1, 'notif_hari_h2', OLD.notif_hari_h2, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_regulasi AFTER UPDATE ON regulasi FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.nomor IS NOT NEW.nomor OR OLD.tahun IS NOT NEW.tahun OR OLD.tentang IS NOT NEW.tentang OR OLD.status IS NOT NEW.status OR OLD.pasal_berlaku IS NOT NEW.pasal_berlaku OR OLD.digantikan_oleh_id IS NOT NEW.digantikan_oleh_id OR OLD.catatan IS NOT NEW.catatan OR OLD.urutan IS NOT NEW.urutan OR OLD.created_at IS NOT NEW.created_at OR OLD.updated_at IS NOT NEW.updated_at OR OLD.updated_by IS NOT NEW.updated_by OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('regulasi', 'ubah', OLD.id, json_object('id', OLD.id, 'nomor', OLD.nomor, 'tahun', OLD.tahun, 'tentang', OLD.tentang, 'status', OLD.status, 'pasal_berlaku', OLD.pasal_berlaku, 'digantikan_oleh_id', OLD.digantikan_oleh_id, 'catatan', OLD.catatan, 'urutan', OLD.urutan, 'created_at', OLD.created_at, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_regulasi AFTER DELETE ON regulasi FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('regulasi', 'hapus', OLD.id, json_object('id', OLD.id, 'nomor', OLD.nomor, 'tahun', OLD.tahun, 'tentang', OLD.tentang, 'status', OLD.status, 'pasal_berlaku', OLD.pasal_berlaku, 'digantikan_oleh_id', OLD.digantikan_oleh_id, 'catatan', OLD.catatan, 'urutan', OLD.urutan, 'created_at', OLD.created_at, 'updated_at', OLD.updated_at, 'updated_by', OLD.updated_by, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_ubah_rekon_bulanan AFTER UPDATE ON rekon_bulanan FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.bulan_tmt IS NOT NEW.bulan_tmt OR OLD.tanggal_input IS NOT NEW.tanggal_input OR OLD.input_by IS NOT NEW.input_by OR OLD.jumlah_data IS NOT NEW.jumlah_data OR OLD.catatan IS NOT NEW.catatan OR OLD.created_at IS NOT NEW.created_at OR OLD.urutan_sisip IS NOT NEW.urutan_sisip
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('rekon_bulanan', 'ubah', OLD.id, json_object('id', OLD.id, 'bulan_tmt', OLD.bulan_tmt, 'tanggal_input', OLD.tanggal_input, 'input_by', OLD.input_by, 'jumlah_data', OLD.jumlah_data, 'catatan', OLD.catatan, 'created_at', OLD.created_at, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_rekon_bulanan AFTER DELETE ON rekon_bulanan FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('rekon_bulanan', 'hapus', OLD.id, json_object('id', OLD.id, 'bulan_tmt', OLD.bulan_tmt, 'tanggal_input', OLD.tanggal_input, 'input_by', OLD.input_by, 'jumlah_data', OLD.jumlah_data, 'catatan', OLD.catatan, 'created_at', OLD.created_at, 'urutan_sisip', OLD.urutan_sisip));
END;

CREATE TRIGGER jejak_data_hapus_users AFTER DELETE ON users FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('users', 'hapus', OLD.id, json_object('id', OLD.id, 'nip', OLD.nip, 'password', OLD.password, 'nama', OLD.nama, 'jabatan', OLD.jabatan, 'email', OLD.email, 'role', OLD.role, 'created_at', OLD.created_at, 'urutan_sisip', OLD.urutan_sisip, 'satker', OLD.satker, 'cadangan_terakhir_at', OLD.cadangan_terakhir_at));
END;

CREATE TRIGGER jejak_data_hapus_audit_log AFTER DELETE ON audit_log FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('audit_log', 'hapus', OLD.id, json_object('id', OLD.id, 'waktu', OLD.waktu, 'aksi', OLD.aksi, 'detail', OLD.detail, 'target_nama', OLD.target_nama, 'ip_address', OLD.ip_address, 'user_id', OLD.user_id, 'urutan_sisip', OLD.urutan_sisip));
END;
