-- Pejabat penetap SK KGB terakhir atau SK CPNS pada usulan UPT (ADR-086), sama dengan migrasi Supabase
-- 20261008150000_usulan_penetap_sk_terakhir.sql. Trigger jejak usulan_pegawai dibuat ulang supaya kolom baru ikut tercatat.

ALTER TABLE usulan_pegawai ADD COLUMN penetap_sk_terakhir TEXT;

DROP TRIGGER IF EXISTS jejak_data_ubah_usulan_pegawai;
DROP TRIGGER IF EXISTS jejak_data_hapus_usulan_pegawai;

CREATE TRIGGER jejak_data_ubah_usulan_pegawai AFTER UPDATE ON usulan_pegawai FOR EACH ROW
WHEN OLD.id IS NOT NEW.id OR OLD.pegawai_id IS NOT NEW.pegawai_id OR OLD.satker IS NOT NEW.satker OR OLD.status IS NOT NEW.status OR OLD.nomor_surat IS NOT NEW.nomor_surat OR OLD.tanggal_surat IS NOT NEW.tanggal_surat OR OLD.path_berkas IS NOT NEW.path_berkas OR OLD.nama IS NOT NEW.nama OR OLD.tempat_lahir IS NOT NEW.tempat_lahir OR OLD.tanggal_lahir IS NOT NEW.tanggal_lahir OR OLD.jenis_kelamin IS NOT NEW.jenis_kelamin OR OLD.pendidikan_terakhir IS NOT NEW.pendidikan_terakhir OR OLD.jabatan IS NOT NEW.jabatan OR OLD.pangkat IS NOT NEW.pangkat OR OLD.golongan_ruang IS NOT NEW.golongan_ruang OR OLD.eselon IS NOT NEW.eselon OR OLD.jenis_jabatan IS NOT NEW.jenis_jabatan OR OLD.tmt_golongan IS NOT NEW.tmt_golongan OR OLD.mkg_tahun IS NOT NEW.mkg_tahun OR OLD.mkg_bulan IS NOT NEW.mkg_bulan OR OLD.gaji_pokok IS NOT NEW.gaji_pokok OR OLD.tmt_kgb_terakhir IS NOT NEW.tmt_kgb_terakhir OR OLD.tmt_kgb_berikutnya IS NOT NEW.tmt_kgb_berikutnya OR OLD.nomor_sk_terakhir IS NOT NEW.nomor_sk_terakhir OR OLD.tanggal_sk_terakhir IS NOT NEW.tanggal_sk_terakhir OR OLD.hukdis_ada IS NOT NEW.hukdis_ada OR OLD.hukdis_jenis IS NOT NEW.hukdis_jenis OR OLD.hukdis_nomor_sk IS NOT NEW.hukdis_nomor_sk OR OLD.hukdis_tmt_mulai IS NOT NEW.hukdis_tmt_mulai OR OLD.hukdis_tmt_berakhir IS NOT NEW.hukdis_tmt_berakhir OR OLD.hukdis_keterangan IS NOT NEW.hukdis_keterangan OR OLD.catatan_upt IS NOT NEW.catatan_upt OR OLD.diajukan_oleh IS NOT NEW.diajukan_oleh OR OLD.diajukan_at IS NOT NEW.diajukan_at OR OLD.ditinjau_oleh IS NOT NEW.ditinjau_oleh OR OLD.ditinjau_at IS NOT NEW.ditinjau_at OR OLD.alasan_tolak IS NOT NEW.alasan_tolak OR OLD.urutan_sisip IS NOT NEW.urutan_sisip OR OLD.jenis IS NOT NEW.jenis OR OLD.nip IS NOT NEW.nip OR OLD.unit_kerja IS NOT NEW.unit_kerja OR OLD.path_sk_terakhir IS NOT NEW.path_sk_terakhir OR OLD.path_syarat_cpns IS NOT NEW.path_syarat_cpns OR OLD.path_sk_pangkat IS NOT NEW.path_sk_pangkat OR OLD.path_sk_cpns IS NOT NEW.path_sk_cpns OR OLD.dasar_baru_jenis IS NOT NEW.dasar_baru_jenis OR OLD.dasar_baru_jenis_kp IS NOT NEW.dasar_baru_jenis_kp OR OLD.dasar_baru_nomor_sk IS NOT NEW.dasar_baru_nomor_sk OR OLD.dasar_baru_tanggal_sk IS NOT NEW.dasar_baru_tanggal_sk OR OLD.dasar_baru_tmt IS NOT NEW.dasar_baru_tmt OR OLD.dasar_baru_penetap IS NOT NEW.dasar_baru_penetap OR OLD.path_sk_pmk IS NOT NEW.path_sk_pmk OR OLD.golongan_acuan IS NOT NEW.golongan_acuan OR OLD.mkg_tahun_acuan IS NOT NEW.mkg_tahun_acuan OR OLD.mkg_bulan_acuan IS NOT NEW.mkg_bulan_acuan OR OLD.keadaan_kgb IS NOT NEW.keadaan_kgb OR OLD.penetap_sk_terakhir IS NOT NEW.penetap_sk_terakhir
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('usulan_pegawai', 'ubah', OLD.id, json_patch(json_patch(json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'status', OLD.status, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'path_berkas', OLD.path_berkas, 'nama', OLD.nama, 'tempat_lahir', OLD.tempat_lahir, 'tanggal_lahir', OLD.tanggal_lahir, 'jenis_kelamin', OLD.jenis_kelamin, 'pendidikan_terakhir', OLD.pendidikan_terakhir, 'jabatan', OLD.jabatan, 'pangkat', OLD.pangkat, 'golongan_ruang', OLD.golongan_ruang), json_object('eselon', OLD.eselon, 'jenis_jabatan', OLD.jenis_jabatan, 'tmt_golongan', OLD.tmt_golongan, 'mkg_tahun', OLD.mkg_tahun, 'mkg_bulan', OLD.mkg_bulan, 'gaji_pokok', OLD.gaji_pokok, 'tmt_kgb_terakhir', OLD.tmt_kgb_terakhir, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya, 'nomor_sk_terakhir', OLD.nomor_sk_terakhir, 'tanggal_sk_terakhir', OLD.tanggal_sk_terakhir, 'hukdis_ada', OLD.hukdis_ada, 'hukdis_jenis', OLD.hukdis_jenis, 'hukdis_nomor_sk', OLD.hukdis_nomor_sk, 'hukdis_tmt_mulai', OLD.hukdis_tmt_mulai, 'hukdis_tmt_berakhir', OLD.hukdis_tmt_berakhir)), json_object('hukdis_keterangan', OLD.hukdis_keterangan, 'catatan_upt', OLD.catatan_upt, 'diajukan_oleh', OLD.diajukan_oleh, 'diajukan_at', OLD.diajukan_at, 'ditinjau_oleh', OLD.ditinjau_oleh, 'ditinjau_at', OLD.ditinjau_at, 'alasan_tolak', OLD.alasan_tolak, 'urutan_sisip', OLD.urutan_sisip, 'jenis', OLD.jenis, 'nip', OLD.nip, 'unit_kerja', OLD.unit_kerja, 'path_sk_terakhir', OLD.path_sk_terakhir, 'path_syarat_cpns', OLD.path_syarat_cpns, 'path_sk_pangkat', OLD.path_sk_pangkat, 'path_sk_cpns', OLD.path_sk_cpns)), json_object('dasar_baru_jenis', OLD.dasar_baru_jenis, 'dasar_baru_jenis_kp', OLD.dasar_baru_jenis_kp, 'dasar_baru_nomor_sk', OLD.dasar_baru_nomor_sk, 'dasar_baru_tanggal_sk', OLD.dasar_baru_tanggal_sk, 'dasar_baru_tmt', OLD.dasar_baru_tmt, 'dasar_baru_penetap', OLD.dasar_baru_penetap, 'path_sk_pmk', OLD.path_sk_pmk, 'golongan_acuan', OLD.golongan_acuan, 'mkg_tahun_acuan', OLD.mkg_tahun_acuan, 'mkg_bulan_acuan', OLD.mkg_bulan_acuan, 'keadaan_kgb', OLD.keadaan_kgb, 'penetap_sk_terakhir', OLD.penetap_sk_terakhir)));
END;

CREATE TRIGGER jejak_data_hapus_usulan_pegawai AFTER DELETE ON usulan_pegawai FOR EACH ROW
BEGIN
  INSERT INTO jejak_data (tabel, aksi, id_baris, lama) VALUES ('usulan_pegawai', 'hapus', OLD.id, json_patch(json_patch(json_patch(json_object('id', OLD.id, 'pegawai_id', OLD.pegawai_id, 'satker', OLD.satker, 'status', OLD.status, 'nomor_surat', OLD.nomor_surat, 'tanggal_surat', OLD.tanggal_surat, 'path_berkas', OLD.path_berkas, 'nama', OLD.nama, 'tempat_lahir', OLD.tempat_lahir, 'tanggal_lahir', OLD.tanggal_lahir, 'jenis_kelamin', OLD.jenis_kelamin, 'pendidikan_terakhir', OLD.pendidikan_terakhir, 'jabatan', OLD.jabatan, 'pangkat', OLD.pangkat, 'golongan_ruang', OLD.golongan_ruang), json_object('eselon', OLD.eselon, 'jenis_jabatan', OLD.jenis_jabatan, 'tmt_golongan', OLD.tmt_golongan, 'mkg_tahun', OLD.mkg_tahun, 'mkg_bulan', OLD.mkg_bulan, 'gaji_pokok', OLD.gaji_pokok, 'tmt_kgb_terakhir', OLD.tmt_kgb_terakhir, 'tmt_kgb_berikutnya', OLD.tmt_kgb_berikutnya, 'nomor_sk_terakhir', OLD.nomor_sk_terakhir, 'tanggal_sk_terakhir', OLD.tanggal_sk_terakhir, 'hukdis_ada', OLD.hukdis_ada, 'hukdis_jenis', OLD.hukdis_jenis, 'hukdis_nomor_sk', OLD.hukdis_nomor_sk, 'hukdis_tmt_mulai', OLD.hukdis_tmt_mulai, 'hukdis_tmt_berakhir', OLD.hukdis_tmt_berakhir)), json_object('hukdis_keterangan', OLD.hukdis_keterangan, 'catatan_upt', OLD.catatan_upt, 'diajukan_oleh', OLD.diajukan_oleh, 'diajukan_at', OLD.diajukan_at, 'ditinjau_oleh', OLD.ditinjau_oleh, 'ditinjau_at', OLD.ditinjau_at, 'alasan_tolak', OLD.alasan_tolak, 'urutan_sisip', OLD.urutan_sisip, 'jenis', OLD.jenis, 'nip', OLD.nip, 'unit_kerja', OLD.unit_kerja, 'path_sk_terakhir', OLD.path_sk_terakhir, 'path_syarat_cpns', OLD.path_syarat_cpns, 'path_sk_pangkat', OLD.path_sk_pangkat, 'path_sk_cpns', OLD.path_sk_cpns)), json_object('dasar_baru_jenis', OLD.dasar_baru_jenis, 'dasar_baru_jenis_kp', OLD.dasar_baru_jenis_kp, 'dasar_baru_nomor_sk', OLD.dasar_baru_nomor_sk, 'dasar_baru_tanggal_sk', OLD.dasar_baru_tanggal_sk, 'dasar_baru_tmt', OLD.dasar_baru_tmt, 'dasar_baru_penetap', OLD.dasar_baru_penetap, 'path_sk_pmk', OLD.path_sk_pmk, 'golongan_acuan', OLD.golongan_acuan, 'mkg_tahun_acuan', OLD.mkg_tahun_acuan, 'mkg_bulan_acuan', OLD.mkg_bulan_acuan, 'keadaan_kgb', OLD.keadaan_kgb, 'penetap_sk_terakhir', OLD.penetap_sk_terakhir)));
END;
